spring.application.name=demo
spring.datasource.url=jdbc:sap://f6423089-ba2c-4eb7-bb5a-e1b6cc195186.hna1.prod-us10.hanacloud.ondemand.com:443?encrypt=true&validateCertificate=true&currentschema=3BD94991548846EE9E58CC290F10E494
spring.datasource.username=3BD94991548846EE9E58CC290F10E494_DCK5B8CX7J4GK8VLIQSDV4WY6_DT
spring.datasource.password=?2{6Dt8P%)u[Ap[F1!@.Zh%edRhlUJa0IXQ^6]ak*~^]A~0K 0m)w^ 11PN4XA!<NL3D~^NKO!ZOPR.&SZ;^HL,~.N+y4=FCKK9V2[h@R!~7B^`ED+{!ZXkzM RrEikD
spring.datasource.driver-class-name=com.sap.db.jdbc.Driver